spring:
    redis:
        # Redis服务器地址
        host: 192.168.1.167
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password: c123456c7
        pool:
           # 连接池最大连接数（使用负值表示没有限制）
           max-active: 8
           # 连接池中的最大空闲连接
           min-idle: 0
           # 连接池最大阻塞等待时间（使用负值表示没有限制）
           max-wait: -1
           # 连接池中的最小空闲连接
           max-idle: 8
        # 连接超时时间（毫秒）
        timeout: 20
#天马的信息配置
tianma: 
    #天马的用户名
    name: 青岛麦巨商贸
    #天马的密码
    pwd: 0929mjmj
    #天马的验证
    remember: on
    
#百度API的接口调用的信息    
baidu: 
   APP_ID: 10940680
   API_KEY: kczT5UXLcRsG8BUe03pFuTek
   SECRET_KEY: wdl08w51UTyV8kLElGypHBulBAZ4Dhnz